### PR TITLE
Add asynchhronous functions

### PR DESCRIPTION
**Pull request by LBertrandDC**
Add two new functions: start a conversion and return immediately, and read temperature.

### CODE REVIEW

**Comment by ladyada** [comment]
@tannewt this is a good opportunity to come up with api naming for async sensor reading. this is gonna come up more & more

**Comment by tannewt** [comment]
I think this naming is fine for now. There is still discussion on https://github.com/adafruit/circuitpython/issues/1380 about it. @dhalbert may have other ideas.

**Comment by LBertrandDC** [comment]
I'm not sure why the Travis build failed. The only problem I see in the build log is pylint "trailing whitespace" on line 124. But there aren't 124 lines in adafruit_ds18x20.py. When I run pylint locally, I get two refactor warnings in the existing code (that I didn't touch).

**Comment by ladyada** [comment]
make sure you are looking at the right code, the file def has 124 lines
https://github.com/adafruit/Adafruit_CircuitPython_DS18X20/blob/5b4058ae140ce95dfd2f0d434ffe604281d11f75/adafruit_ds18x20.py#L124

**Comment by LBertrandDC** [comment]
OK, removed extra blanks from line 124.
Thanks
 --Louis

**Review by tannewt — APPROVED** [review]
Looks great! Thank you!

**Comment by LBertrandDC** [comment]
You’re welcome. Now, what happens to the issue #11 ? Should it be closed? By whom?
Thanks
--Louis

**Comment by tannewt** [comment]
I've closed it. Next time you can use a keyword in a commit message to have the issue closed automatically when the commit is merged: https://help.github.com/en/articles/closing-issues-using-keywords Thanks!

**Pull request merged**
